name: Deploy Angular Application

on:
  push:
    branches: [feature]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: basith7618/angular-app:latest
          cache-from: type=registry,ref=basith7618/angular-app:buildcache
          cache-to: type=registry,ref=basith7618/angular-app:buildcache,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from dockerhub
        run: docker pull basith7618/angular-app:latest

      - name: Delete old container
        run: docker rm -f angular-app-container || true

      - name: Run docker container
        run: |
          docker run -d \
            -p 4200:80 \
            --name angular-app-container \
            --restart unless-stopped \
            -e NODE_ENV=production \
            basith7618/angular-app
