name: Deploy Angular Application

on:
  push:
    branches: [feature]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSSWORD }}

      - name: Generate version
        id: version
        run: echo "::set-output name=version::$(date +%s)"

      - name: Build docker image
        run: |
          docker build --no-cache -t basith7618/angular-app .
          docker tag basith7618/angular-app:latest basith7618/angular-app:$(date +%s)

      - name: Publish image to dockerhub
        run: |
          docker push basith7618/angular-app:latest
          docker push basith7618/angular-app:${{ steps.version.outputs.version }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean up
        run: docker system prune -f
      - name: Pull image from dockerhub
        run: docker pull basith7618/angular-app:latest
      - name: Delete old container
        run: docker rm -f angular-app-container ||true
      - name: Run docker container
        run: docker run -d -p 4200:80 --name angular-app-container  --restart unless-stopped  basith7618/angular-app
      - name: Debug container
        run: |
          echo "Container logs:"
          docker logs angular-app-container
          echo "Container status:"
          docker ps -a
          echo "Images available:"
          docker images
