name: Deploy Angular Application

on:
  push:
    branches: [feature]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSSWORD }}
      - name: Build docker image
        run: docker build -t basith7618/angular-app .
      - name: Publish image to dockerhub
        run: docker push basith7618/angular-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from dockerhub
        run: docker pull basith7618/angular-app:latest
      - name: Delete old container
        run: docker rm -f basith7618/angular-app
      - name: Run docker container
        run: docker run -d -p 4200:80 --name angular-app-container  basith7618/angular-app
